### ISSUE TITLE
codeworld-api-2.1.0: install failed 

### ISSUE THREAD

**Issue by kaustubhhiware** [google/codeworld#484]
Hi, I have recently tried to reinstall codeworld and I'm getting the following error when I'm trying to build [`./build.sh`]

```
Building codeworld-api-0.2.1.0...
Preprocessing library codeworld-api-0.2.1.0...
[5 of 6] Compiling CodeWorld.Driver ( src/CodeWorld/Driver.hs, dist/build/CodeWorld/Driver.js_o )

src/CodeWorld/Driver.hs:86:1: error:
    Failed to load interface for ‘GHCJS.DOM.ClientRect’
    Use -v to see a list of the files searched for.
cabal: Leaving directory './codeworld-api/'
cabal: Error: some packages failed to install:
codeworld-api-0.2.1.0 failed during the building phase. The exception was:
ExitFailure 1
codeworld-base-0.2.0.0 depends on codeworld-api-0.2.1.0 which failed to
install.
============================
= Aborting: Command failed =
============================
````
I tried debugging and googling, but that didn't help a lot. Any plausible cause for this error ?
The current latest commit is `c33df7c`

**Comment by cdsmith** [comment]
Seems to be caused by https://github.com/ghcjs/ghcjs-dom/commit/3c495cd71b2bdcc2013d305d2fab944fd9b5650a

Now to find the fix...

**Comment by cdsmith** [comment]
Some more quick research: the replacement seems to be GHCJS.DOM.DOMRect.  However, the members `left` and `top` have been replaced by `x` and `y`.  I want to be sure this works in other browsers before committing to it.  Until then, one fix would be to choose a specific commit for the ghcjs-dom dependency in `install.sh`.  Anything before https://github.com/ghcjs/ghcjs-dom/commit/3c495cd71b2bdcc2013d305d2fab944fd9b5650a should do fine.

**Comment by cdsmith** [comment]
Opened https://github.com/ghcjs/ghcjs-dom/issues/69 to track the underlying blocker for migration.  Until then, I'll modify install.sh to install the older ghcjs-dom version.

**Comment by cdsmith** [comment]
I've pushed some fixes, and this should install and build from a fresh checkout.

I switched away from using the git version of ghcjs-dom, to hackage.  The version from git was necessary in the early days of the project, but isn't needed any more.  That allows me to add version bounds, and I've done so to exclude the 0.9 version that deleted ClientRect.

The long-term solution is to migrate this code to use DOMRectReadOnly instead, but I'm unclear on how to do so.  The bug against ghcjs-dom addresses that.

**Comment by hamishmack** [comment]
> The long-term solution is to migrate this code to use DOMRectReadOnly instead, but I'm unclear on how to do so.

There is an `instance IsDOMRectReadOnly DOMRect` in `GHCJS.DOM.Types`, so you can use all the functions in `GHCJS.DOM.DOMRectReadOnly` with `DOMRect`.

It also means you can use `GHCJS.DOM.Types.toDOMRectReadOnly` on a `DOMRect` to get a `DOMRectReadOnly` (this does not actually copy the object so if you use the `set*` functions on the `DOMRect` they will mutate the `DOMRectReadOnly` as well).
