### ISSUE TITLE
codeworld-api doesn't compile on 9.2.4

### ISSUE THREAD

**Issue by GeorgeCo** [google/codeworld#1584]
Codeworld doesn't compile on 9.2.4. It would be great if that could be fixed. I am very impressed by codeworld.
When I compile with --allow-new it fails with 

```
[ 9 of 16] Compiling CodeWorld.Driver ( src/CodeWorld/Driver.hs, dist/build/CodeWorld/Driver.o, dist/build/CodeWorld/Driver.dyn_o )

src/CodeWorld/Driver.hs:1046:1: error:
    Duplicate instance declarations:
      instance Generic Fingerprint
        -- Defined at src/CodeWorld/Driver.hs:1046:1
      instance Generic Fingerprint -- Defined in ‘GHC.Generics’
     |
1046 | deriving instance Generic Fingerprint
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build codeworld-api-0.7.0. See the build log above for
details.
```

**Comment by marcellussiegburg** [comment]
This is also the case on ghc-9.0.2.

**Comment by cdsmith** [comment]
Sorry I haven't gotten to this.  It's not too difficult to fix, but I just have been focused on other things.  It's on my list now.

**Comment by GeorgeCo** [comment]
Thanks Chris, that's great news!

**Comment by cdsmith** [comment]
Fixed.  Sorry for the delay!

Unfortunately, I wasn't able to test with GHC 9.4 yet, because reflex is still not updated.  I have relaxed the version bounds on codeworld-api itself, though, so this will hopefully be possible as soon as reflex is updated.
